Repository darakbooks-project/darakbooks-FE, pull requests merged in 2023-07, with the labels that each got.

#341 Design/#325 mypage
  public/images/profile/back-arrow.svg
  public/images/profile/bin.svg
  public/images/profile/delete.svg
  public/images/profile/logout.svg
  public/images/profile/pencil.svg
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/recoil/modal.ts
Labels: 💄Design

#342 feat & design: 마이 모임 디자인, 클릭 시 상세페이지 이동
  src/pages/profile/myrecruit.tsx
Labels: ✨ Feature, 💄Design

#344 Design/#343 record icon
  public/images/profile/red-delete.svg
  src/pages/profile/myfeed.tsx
Labels: 💄Design

#346 design: 추천페이지 글씨 반응형으로 변경
  .gitignore
  src/components/recommend/BookRecommendGuide.tsx
  src/components/recommend/RecommendLoading.tsx
  src/components/recommend/RecommendResultModal.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
  tailwind.config.js
Labels: 💄Design

#349 design: 독서 모임 상세 일러스트 적용
  public/images/group/group-detail-illust.svg
  src/pages/recruit/detail/index.tsx
Labels: 💄Design

#350 design: 메인페이지 일러스트 및 반응형 적용
  public/images/main/gpt-move.svg
  public/images/main/gpt-recommend.svg
  public/images/main/main-banner.svg
  public/images/main/main-logo.svg
  src/components/main/bestRecruit/BestRecruitList.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/pages/index.tsx
Labels: 💄Design

#352 Feat/#351 select page
  src/components/book/record/SelectModal.tsx
  src/components/book/search/InfinityScrollLists.tsx
  src/layout/BookSelectLayout.tsx
  src/pages/book/record/select.tsx
  책
Labels: ✨ Feature, 💄Design

#354 Feat/#345 router loading
  public/images/loading.svg
  src/components/common/LoadingSpinner.tsx
  src/hooks/useRouterLoading.ts
  src/pages/_app.tsx
Labels: ✨ Feature

#356 Feat/#353 mypage
  src/layout/ProfileLayout.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: ✨ Feature, 💄Design

#359 feat: 메인 기록 무한스크롤 페이지 이동 시 스크롤 유지
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/hooks/useRememberScroll.ts
  src/pages/book/record/index.tsx
Labels: ✨ Feature

#361 design: 독서 모임 상세 페이지 디자인 변경사항적용
  public/images/group/group-leader.svg
  src/components/common/Header.tsx
  src/components/common/Modal.tsx
  src/components/recruit/detail/RecruitNotification.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/RecruitStatusSelectModal.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
  tailwind.config.js
Labels: 💄Design

#358 design: 글꼴 설정
  public/fonts/.keep
  public/fonts/Cafe24Oneprettynight-v2.0.woff2
  src/pages/_app.tsx
  tailwind.config.js
Labels: 💄Design

#366 Feat/#365 detail page
  public/images/detail/upper-arrow.svg
  src/pages/book/detail/index.tsx
  책
Labels: ✨ Feature, 💄Design

#368 fix: 폰트 상대경로 수정
  src/pages/_app.tsx
Labels: 🐞 BugFix

#370 feat: 스킵 버튼 클릭 시 마지막 슬라이드로 이동
  src/pages/onboarding/index.tsx
  src/styles/globals.css
Labels: ✨ Feature

#372 design: 메인페이지 디자인 수정사항 적용
  src/components/common/BookShelfPreview.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: 💄Design

#374 refactor: 추천페이지 수정 사항 적용
  src/api/book.ts
  src/components/recommend/BookRecommendGuide.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
Labels: 🔨 Refactor, 💄Design

#369 design: 독서 모임 개설, 수정 페이지 아이콘 설정
  src/components/recruit/RecruitFormUserInput.tsx
Labels: 💄Design

#378 fix: 마이 피드 편집 버튼 클릭시 화면이 줄어드는 현상 해결
  src/pages/profile/myfeed.tsx
Labels: 🐞 BugFix

#380 design: 외 n명 높이 수정
  src/pages/profile/myrecruit.tsx
Labels: 💄Design

#382 feat: 도서 상세 페이지 스크롤 위치 기억
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
Labels: ✨ Feature

#390 design: 도서 검색 페이지 검색 결과 없을 시 comment 설정
  src/components/book/search/InfinityScrollLists.tsx
Labels: 💄Design

#391 design: 로그인 페이지 디자인 수정
  src/components/auth/LoginButton.tsx
  src/pages/login/index.tsx
Labels: 💄Design

#392 design: 독서 모임 조회 페이지 디자인 수정
  public/images/group/reading-group-illustration.svg
  public/images/reading-group-illustration.svg
  src/pages/recruit/index.tsx
Labels: 💄Design

#393 design: 독서 모임 개설, 수정 페이지 온라인 버튼 클릭 시
  src/components/recruit/RecruitFormUserInput.tsx
Labels: 💄Design

#395 design: 로그인 중이에요 comment 제거
  src/pages/oauth/callback/kakao.tsx
Labels: 💄Design

#396 fix: 도서 검색 결과 유지되는 문제
  src/layout/ProfileLayout.tsx
Labels: 🐞 BugFix

#402 design: 독서 기록 페이지 폰트 적용
  src/pages/book/record/index.tsx
Labels: 💄Design

#403 design: 피드 상세 페이지 폰트 적용
  src/pages/book/feed/index.tsx
Labels: 💄Design

#406 fix: 도서 검색 페이지, 도서 선택 페이지 검색 탭 기록이 공유되는 현상 해결
  src/components/book/search/InfinityScrollLists.tsx
  src/pages/book/record/search.tsx
Labels: 🐞 BugFix

#408 fix: 메인 피드 데스크탑 모드 시 이미지 안보임 해결
  src/components/main/mainRecordFeed/FeedItem.tsx
Labels: 🐞 BugFix, 💄Design

#411 design: 뒤로가기, 달력 버튼 수정
  public/images/record/calendar-left.svg
  public/images/record/calendar-right.svg
  src/pages/book/record/index.tsx
  src/styles/globals.css
Labels: 💄Design

#413 design: 배경 추가, 뒤로가기 추가
  src/pages/book/feed/index.tsx
Labels: 💄Design

#415 feat: 검색 엔진 최적화를 위한 공통컴포넌트 생성
  public/favicon.svg
  src/components/common/Seo.tsx
  src/pages/_document.tsx
Labels: ✨ Feature

#419 design: 추천페이지(로딩/결과) 디자인 수정 사항 적용
  public/images/bookRecommend/recommendLoadingCharacter.svg
  src/components/recommend/RecommendLoading.tsx
  src/components/recommend/RecommendResultModal.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
  src/recoil/modal.ts
  src/recoil/recommend.ts
Labels: 💄Design

#418 chore: bundle-analyzer 설치
  next.config.js
  package.json
  yarn.lock
Labels: ✏️ Chore

#421 refactor: 온라인일 경우 지역 데이터 없음을 나타내는 문자열 전달
  src/hooks/useGroupForm.ts
Labels: 🔨 Refactor

#423 design: font 수정 작업
  src/components/common/BottomNav.tsx
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/recruit/RecruitForm.tsx
  src/components/recruit/RecruitFormUserInput.tsx
  src/pages/book/search/index.tsx
  src/pages/login/index.tsx
  src/pages/recruit/index.tsx
Labels: 💄Design

#428 chore: ga 연동
  package.json
  src/lib/gtag.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  yarn.lock
Labels: ✏️ Chore

#427 fix: 모집여부 변경 모달 낙관적 업데이트 적용
  src/components/recruit/detail/RecruitStatusSelectModal.tsx
Labels: 🐞 BugFix

#431 fix: 뒤로가기 시 스크롤 하단으로 움직임 수정
  src/pages/_app.tsx
Labels: 🐞 BugFix

#432 refactor: 일정 시간 이상 걸리는 로딩만 스피너 보이도록 처리
  src/hooks/useRouterLoading.ts
Labels: 🔨 Refactor

#435 docs: README 작성
  README.md
Labels: 📃 Docs

#437 fix: 추천 책장 없을 때 처리
  src/components/main/bestRecruit/BestRecruitList.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/pages/index.tsx
Labels: 🐞 BugFix, 💄Design

#439 docs: 리드미 프로필 수정
  README.md
Labels: 📃 Docs

#444 fix: 추천 책장 에러처리 적용
  src/pages/index.tsx
Labels: 🐞 BugFix

#442 design: 추천페이지 로딩 배경 적용
  public/images/bookRecommend/background-loading.svg
  src/components/recommend/RecommendLoading.tsx
Labels: 💄Design

#446 design: 독서 모임 조회 페이지 하얀색 배경 영역 확장
  src/pages/recruit/index.tsx
Labels: 💄Design

#450 design: 책 제목 가운데 정렬
  src/pages/book/detail/index.tsx
Labels: 💄Design

#452 feat: 404
  public/images/notfound/not-found.svg
  src/pages/404.tsx
Labels: ✨ Feature

#447 fix: ga 관련 코드 수정
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: 🐞 BugFix

#454 design: 도서 선택 모달 책 제목 가운데 정렬
  src/components/book/record/SelectModal.tsx
Labels: 💄Design

#456 design: 메인, 독서 모임 상세페이지 디자인 수정
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/pages/recruit/detail/index.tsx
Labels: 💄Design

#458 refactor: 추천페이지 수정
  src/components/recommend/BookRecommendGuide.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
Labels: 🔨 Refactor, 💄Design

#461 chore: remove @next/font
  package.json
  yarn.lock
Labels: ✏️ Chore

#464 Refactor/#462 optimization record
  .eslintignore
  next.config.js
  package.json
  src/components/book/record/DatePickerComponent.tsx
  src/components/common/Header.tsx
  src/pages/book/record/index.tsx
Labels: 🔨 Refactor

#471 design: favicon 수정
  public/favicon.svg
Labels: 💄Design

#475 refactor: 사용하지 않는 이미지 파일 제거
  public/images/bookCover/image1.jpg
  public/images/bookCover/image2.jpg
  public/images/bookCover/image3.jpg
  public/images/bookCover/image4.jpg
  public/images/bookCover/image5.jpg
Labels: 🔨 Refactor

#466 refactor: 도서 검색 페이지 성능 개선
  src/pages/book/search/index.tsx
Labels: 🔨 Refactor

#469 refactor: 로그인 페이지 성능 최적화
  src/pages/login/index.tsx
Labels: 🔨 Refactor

#473 refactor: 고운밤 폰트 import 위치 변경
  src/layout/PrettyNightFontLayout.tsx
  src/pages/_app.tsx
  src/pages/book/feed/index.tsx
  src/pages/book/record/index.tsx
  src/pages/onboarding/index.tsx
Labels: 🔨 Refactor

#467 refactor: 메인페이지 최적화
  src/components/common/BookShelfPreview.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/main/bestRecruit/BestRecruitList.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/components/main/recommendBookShelf/BookShelfPreview.tsx
  src/components/recruit/RecruitTab.tsx
  src/layout/Layout.tsx
  src/layout/RecruitLayout.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: 🔨 Refactor

#476 feat: 담당 페이지 SEO 컴포넌트 적용
  src/pages/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/intro.tsx
  src/pages/recommend/userinput.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
Labels: ✨ Feature

#481 design: 고운밤 layout 컴포넌트 height 100% 설정
  src/layout/PrettyNightFontLayout.tsx
Labels: 💄Design

#479 refactor: 이미지 priority 설정
  src/pages/onboarding/index.tsx
Labels: 🔨 Refactor

#477 Feat/#448 inject seo
  src/components/common/Seo.tsx
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
  src/pages/book/record/index.tsx
  src/pages/book/record/search.tsx
  src/pages/book/record/select.tsx
  src/pages/bookshelf/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
  src/utils/helpers/suitableDescriptionHandler.ts
Labels: ✨ Feature

#483 design: 디자인 수정 사항 반영
  public/images/kakao-logo.svg
  src/pages/login/index.tsx
  src/pages/recruit/index.tsx
Labels: 💄Design

#485 feat: SEO 컴포넌트 적용
  src/components/recruit/RecruitForm.tsx
  src/pages/book/search/index.tsx
  src/pages/login/index.tsx
  src/pages/recruit/index.tsx
Labels: ✨ Feature

#491 fix: 도서 검색 페이지 새로고침 시 렌더링 안되는 문제
  src/pages/book/search/index.tsx
Labels: 🐞 BugFix

#493 refactor: 사용하지 않는 공통 컴포넌트 제거
  src/components/book/search/SearchResultList.tsx
  src/components/common/Avartar.tsx
  src/components/common/BookShelf.tsx
  src/components/common/ImageComponent.tsx
  src/components/common/ListItem/BookSelection.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/common/Tab/index.tsx
  src/components/common/Toggle/index.tsx
  src/components/common/Toggle/useToggle.ts
Labels: 🔨 Refactor

#495 Design/#494 update UI
  src/components/common/BottomNav.tsx
  src/components/common/Modal/Confirm.tsx
Labels: 💄Design

#489 feat: 상세 페이지 썸네일 속성 변경
  src/pages/book/detail/index.tsx
Labels: ✨ Feature

#488 refactor: sementic tag 적용
  src/components/book/search/InfinityScrollLists.tsx
  src/components/common/Header.tsx
  src/components/common/ListItem/ReadingGroupRecruitment.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/recruit/RecruitForm.tsx
  src/components/recruit/RecruitFormUserInput.tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/components/recruit/RecruitList.tsx
  src/pages/book/search/index.tsx
  src/pages/login/index.tsx
  src/pages/recruit/index.tsx
Labels: 🔨 Refactor

#499 refactor: DX 보완
  public/images/setting.svg
  src/api/recruit.ts
  src/components/book/record/DatePickerComponent.tsx
  src/components/book/record/SelectModal.tsx
  src/components/book/search/InfinityScrollLists.tsx
  src/components/common/BottomNav.tsx
  src/components/common/ListItem/ReadingGroupRecruitment.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/main/bestRecruit/BestRecruitList.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/components/main/recommendBookShelf/BookShelfPreview.tsx
  src/components/recommend/BookRecommendGuide.tsx
  src/components/recruit/RecruitForm.tsx
  src/components/recruit/RecruitFormUserInput.tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/RecruitStatusSelectModal.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/hooks/useGroupForm.ts
  src/layout/ProfileLayout.tsx
  src/pages/404.tsx
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
  src/pages/book/record/index.tsx
  src/pages/book/record/select.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
  src/pages/recommend/complete.tsx
  src/pages/recruit/update.tsx
  src/pages/recruit/write.tsx
  src/types/recruit.d.ts
  tailwind.config.js
Labels: 🔨 Refactor

#509 refactor: 프로필 페이지 최적화
  src/layout/ProfileLayout.tsx
  src/pages/book/feed/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: 🔨 Refactor

#506 design: 폰트 사이즈 11px -> 12px 변경
  src/pages/profile/edit.tsx
Labels: 💄Design

#511 refactor: 도서 선택 페이지 최적화
  src/pages/book/record/search.tsx
  src/pages/book/record/select.tsx
Labels: 🔨 Refactor

#508 refactor: 피드 페이지 최적화
  src/pages/book/feed/index.tsx
Labels: 🔨 Refactor

#497 design: 디자인 수정 사항 반영
  public/images/bookRecommend/recommendCharacter.svg
  src/pages/index.tsx
  src/pages/recommend/userinput.tsx
  tailwind.config.js
Labels: 💄Design

#501 refator: 스크롤 위치 기억 Hook으로 수정
  src/components/common/ListItem/ReadingGroupRecruitment.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/pages/book/search/index.tsx
  src/pages/recruit/index.tsx
  src/recoil/book.ts
  src/recoil/recruit.ts
Labels: 🔨 Refactor

#515 feat: 이미지 등록 제한 용량 수정
  src/constants/file.ts
Labels: ✨ Feature

#517 docs: README 배포 url 수정
  README.md
Labels: 📃 Docs
