Repository darakbooks-project/darakbooks-FE, pull requests merged in 2023-05, with the labels that each got.

#20 chore: react-query hydration 설정변경
  src/pages/_app.tsx
Labels: ✏️ Chore

#22 feat: 도서 기록 페이지 라우트 설정
  package.json
  src/constants/.keep
  src/constants/file.ts
  src/pages/book/detail/index.tsx
  src/pages/book/record/index.tsx
  yarn.lock
Labels: ✨ Feature

#18 feat: 피드 이미지, 그 외 이미지 공통 컴포넌트 구현
  .eslintrc.json
  src/components/.keep
  src/components/common/BookImage.tsx
Labels: ✨ Feature

#32 fix: 빌드 오류 해결
  src/components/common/Avartar.tsx
Labels: 🐞 BugFix

#40 Refactor/#33 book detail page
  src/api/.keep
  src/api/dummy.ts
  src/components/book/detail/BookDescription.tsx
  src/components/book/detail/BookItem.tsx
  src/components/book/detail/BookList.tsx
  src/components/book/detail/Buttons.tsx
  src/components/common/ListItem/BookSelection.tsx
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/common/ListItem/SearchResult.tsx
  src/pages/book/detail/index.tsx
  src/styles/.keep
Labels: 🔨 Refactor

#42 Feat/#41 tags input
  src/pages/book/record/index.tsx
Labels: ✨ Feature

#44 Refactor/#43 book record page
  src/components/book/record/RecordForm.tsx
  src/components/book/record/RecordHeader.tsx
  src/hooks/.keep
  src/hooks/useInput.ts
  src/pages/book/record/index.tsx
Labels: 🔨 Refactor

#46 feat: 소셜 로그인 구현
  public/images/login-image.svg
  src/api/auth.ts
  src/components/auth/LoginButton.tsx
  src/components/common/BottomNav.tsx
  src/constants/auth.ts
  src/hooks/useAuth.ts
  src/pages/login/index.tsx
  src/pages/oauth/callback/kakao.tsx
  src/recoil/.keep
  src/recoil/atom/auth.ts
Labels: ✨ Feature

#53 fix: 새로고침 시 로그아웃되는 문제 해결
  src/api/auth.ts
  src/components/common/BottomNav.tsx
  src/hooks/useAuth.ts
  src/pages/oauth/callback/kakao.tsx
  src/recoil/atom/auth.ts
Labels: 🐞 BugFix, ✨ Feature

#54 feat: 로그인 여부 모달 제작
  src/components/auth/LoginModal.tsx
  src/components/common/BottomNav.tsx
  src/pages/_app.tsx
Labels: ✨ Feature

#55 feat: 비 로그인 유저가 url을 통해 유저 전용페이지로 이동 시 막기
  src/components/auth/AuthRequiredPage.tsx
  src/pages/book/record/index.tsx
Labels: ✨ Feature

#68 chore: recoil 하위 폴더 atom 제거
  src/components/auth/AuthRequiredPage.tsx
  src/components/auth/LoginModal.tsx
  src/components/common/BottomNav.tsx
  src/hooks/useAuth.ts
  src/pages/oauth/callback/kakao.tsx
  src/recoil/auth.ts
Labels: ✏️ Chore

#69 chore: tailwind-styled-component 설치
  package.json
  src/components/auth/LoginButton.tsx
  yarn.lock
Labels: ✏️ Chore

#67 feat: 메인 페이지 레이아웃 구현
  package.json
  src/components/common/BookShelfPreview.tsx
  src/components/common/ImageComponent.tsx
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: ✏️ Chore, ✨ Feature

#76 Feat/#75 modal component
  src/components/common/Modal.tsx
  src/pages/_document.tsx
  src/pages/profile/index.tsx
  src/recoil/modal.ts
  tailwind.config.js
Labels: ✨ Feature

#78 feat: 프로필 정보 수정, 글 목록 레이아웃
  src/components/book/record/RecordForm.tsx
  src/components/common/Modal.tsx
  src/pages/profile/index.tsx
  src/recoil/modal.ts
Labels: ✨ Feature

#80 Refactor/#79 myprofile refactor
  src/components/book/record/RecordForm.tsx
  src/components/profile/ProfileContents.tsx
  src/components/profile/ProfileUser.tsx
  src/hooks/useImage.ts
  src/pages/book/record/index.tsx
  src/pages/profile/index.tsx
Labels: 🔨 Refactor, ✨ Feature

#85 feat: 도서 검색 페이지 제작 2
  package.json
  src/api/book.ts
  src/components/book/search/InfinityScrollLists.tsx
  src/components/book/search/SearchResultList.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/pages/_app.tsx
  src/pages/book/search/index.tsx
  yarn.lock
Labels: 🔨 Refactor, ✨ Feature

#88 Api/#87 register image api
  next.config.js
  src/api/image.ts
  src/components/book/record/RecordForm.tsx
  src/components/profile/ProfileUser.tsx
  src/hooks/useImage.ts
Labels: 🔑 API, ✨ Feature

#94 Design/#93 book detail design
  src/components/book/detail/BookDescription.tsx
  src/pages/book/detail/index.tsx
  src/styles/globals.css
Labels: 💄Design

#103 design: 독서 기록 페이지 디자인
  src/components/book/record/Calendar.module.css
  src/components/book/record/RecordForm.tsx
  src/components/book/record/RecordHeader.tsx
  src/components/profile/ProfileUser.tsx
  src/hooks/useImage.ts
  src/pages/book/record/index.tsx
  src/styles/globals.css
Labels: 💄Design

#101 Design/#98 detail feed
  public/images/.keep
  src/pages/book/feed/index.tsx
Labels: 💄Design
