Repository darakbooks-project/darakbooks-FE, pull requests merged in 2023-06, with the labels that each got.

#90 feat: 기존 액세스 토큰 유효기간 만료 시 새로운 액세스 토큰 발급
  src/api/auth.ts
  src/api/axios.ts
  src/pages/oauth/callback/kakao.tsx
  src/utils/helpers/axiosHandler.ts
Labels: ✨ Feature

#96 feat: 독서 인원 모집 페이지 제작
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/pages/recruit/index.tsx
Labels: ✨ Feature

#106 chore: install @next/font
  package.json
  yarn.lock
Labels: ✏️ Chore

#104 Api/#89 book record api
  src/api/image.ts
  src/api/record.ts
  src/components/profile/ProfileUser.tsx
  src/hooks/useImage.ts
  src/pages/book/record/index.tsx
  src/types/record.d.ts
Labels: 🔑 API

#99 feat: 독서 인원 모집 개설 페이지 제작
  src/components/common/Header.tsx
  src/components/recruit/RecruitOpenForm.tsx
  src/constants/region.ts
  src/pages/recruit/write.tsx
  src/types/recruit.d.ts
Labels: ✨ Feature

#108 fix: 도서 검색 페이지 보완 및 에러 해결
  src/components/book/search/InfinityScrollLists.tsx
  src/components/book/search/SearchResultList.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/pages/book/search/index.tsx
  src/recoil/book.ts
Labels: 🐞 BugFix, ✨ Feature

#110 Feat/#107 receive book from detail
  next.config.js
  src/api/book.ts
  src/pages/book/detail/index.tsx
  src/pages/book/record/index.tsx
  src/types/record.d.ts
Labels: ✨ Feature

#109 design: 메인페이지 디자인 적용
  package.json
  public/images/bookCover/image1.jpg
  public/images/bookCover/image2.jpg
  public/images/bookCover/image3.jpg
  public/images/bookCover/image4.jpg
  public/images/bookCover/image5.jpg
  src/components/common/BookShelfPreview.tsx
  src/components/common/ImageComponent.tsx
  src/components/main/BestRecruit.tsx/BestRecruitList.tsx
  src/components/main/BestRecruit.tsx/BestRecruitListItem.tsx
  src/components/main/FeedItem.tsx
  src/pages/index.tsx
  src/types/images.d.ts
  tailwind.config.js
  yarn.lock
Labels: 💄Design

#115 Api/#114 book detail api
  src/pages/book/detail/index.tsx
  src/pages/book/record/index.tsx
  src/types/book.d.ts
Labels: 🔨 Refactor, 🔑 API

#118 fix: 파일 등록 api return 변수명 변경
  src/hooks/useImage.ts
Labels: 🐞 BugFix

#125 design: 변경된 디자인 적용
  src/pages/book/feed/index.tsx
Labels: 💄Design

#127 Feat/#126 dynamic routing
  src/api/book.ts
  src/pages/book/detail/index.tsx
Labels: ✨ Feature, 💄Design

#119 feat: 로그아웃 기능 구현
  src/api/auth.ts
  src/api/axios.ts
  src/pages/book/search/index.tsx
  src/recoil/auth.ts
  src/utils/helpers/axiosHandler.ts
Labels: ✨ Feature

#130 design: 메인 페이지 디자인 변경 사항 반영
  src/components/common/Avartar.tsx
  src/components/common/BookShelfPreview.tsx
  src/components/main/BestRecruit.tsx/BestRecruitList.tsx
  src/components/main/BestRecruit.tsx/BestRecruitListItem.tsx
  src/types/layout.d.ts
  src/types/recruit.d.ts
Labels: 💄Design

#134 design: 도서 선택 페이지 디자인
  src/components/book/record/SelectModal.tsx
  src/layout/BookSelectLayout.tsx
  src/pages/book/record/search.tsx
  src/pages/book/record/select.tsx
  src/recoil/modal.ts
  tailwind.config.js
Labels: 💄Design

#137 fix: enabled 설정
  src/pages/book/record/index.tsx
Labels: 🐞 BugFix

#141 feat: 마이 페이지 라우트 구성
  src/pages/profile/edit.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: ✨ Feature

#133 design: 도서 검색 페이지
  public/images/close.svg
  public/images/search.svg
  src/components/common/ImageComponent.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/common/SearchInput.tsx
  src/pages/book/search/index.tsx
Labels: 💄Design

#139 feat: 독서 모임 개설
  src/api/recruit.ts
  src/components/recruit/RecruitOpenForm.tsx
  src/constants/recruit.ts
  src/constants/region.ts
  src/pages/recruit/write.tsx
  src/types/recruit.d.ts
Labels: ✨ Feature

#142 design: 마이 페이지 디자인
  src/layout/ProfileLayout.tsx
  src/pages/book/record/select.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: 💄Design

#146 design: 독서 모임 상세 페이지 디자인 적용
  src/components/common/Avartar.tsx
  src/components/main/BestRecruit.tsx/BestRecruitListItem.tsx
  src/components/recruit/detail/RecruitNotification.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/pages/recruit/chatting.tsx
  src/pages/recruit/detail.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
Labels: 💄Design

#149 Api/#145 book record
  src/api/dummy.ts
  src/api/record.ts
  src/components/book/detail/.keep
  src/components/book/detail/BookItem.tsx
  src/components/book/detail/BookList.tsx
  src/components/book/detail/Buttons.tsx
  src/pages/book/detail/index.tsx
  src/pages/book/record/index.tsx
  src/types/record.d.ts
Labels: 🔑 API

#143 refactor: 독서 모임 조회 페이지
  src/api/recruit.ts
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/components/recruit/RecruitList.tsx
  src/pages/recruit/index.tsx
  src/recoil/recruit.ts
  src/types/recruit.d.ts
Labels: 🔨 Refactor, ✨ Feature

#150 feat: 독서 모임 멤버 페이지 구현
  src/components/common/Header.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/layout/Layout.tsx
  src/pages/recruit/detail/member.tsx
  src/styles/globals.css
Labels: ✨ Feature, 💄Design

#156 feat: 독서 모임 상세 페이지 api 연결
  src/api/recruit.ts
  src/pages/recruit/detail/index.tsx
Labels: 🔑 API

#159 Api/#158 mypage
  src/api/profile.ts
  src/hooks/useImage.ts
  src/layout/ProfileLayout.tsx
  src/pages/book/search/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: 🔑 API

#153 design: 독서 모임 개설
  public/images/not-select-arrow.svg
  public/images/select-arrow.svg
  src/api/recruit.ts
  src/components/common/Header.tsx
  src/components/recruit/RecruitOpenForm.tsx
  src/pages/recruit/write.tsx
  src/types/recruit.d.ts
Labels: 🔨 Refactor, 💄Design

#155 desgin: 독서 모임 리스트 페이지
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/pages/recruit/index.tsx
Labels: 💄Design

#162 feat: 도서 상세 페이지 무한스크롤
  src/api/book.ts
  src/api/record.ts
  src/pages/book/detail/index.tsx
Labels: ✨ Feature

#170 api: 피드 페이지네이션 구현
  next.config.js
  src/api/record.ts
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
Labels: 🔑 API

#172 feat: 메인페이지 인기 모임, 독서 기록 api 연결
  package.json
  src/api/main.ts
  src/components/main/BestRecruit.tsx/BestRecruitList.tsx
  src/components/main/FeedItem.tsx
  src/components/main/bestRecruit/BestRecruitList.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/pages/index.tsx
  src/types/colorThief.d.ts
  src/types/record.d.ts
  src/types/recruit.d.ts
  yarn.lock
Labels: 🔑 API, ✨ Feature

#173 Feat/#171 profile edit
  src/api/profile.ts
  src/layout/ProfileLayout.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
Labels: 🔑 API, ✨ Feature, 💄Design

#174 design: 나의 모임
  src/pages/profile/myrecruit.tsx
Labels: 💄Design

#165 chore: axiosInstance baseURL 설정
  src/api/auth.ts
  src/api/axios.ts
  src/api/bookshelf.ts
  src/api/profile.ts
  src/api/record.ts
  src/api/recruit.ts
Labels: ✏️ Chore

#166 feat: 로그인이 필요한 곳에 Login Modal Render
  src/components/common/BookShelfPreview.tsx
  src/components/common/BottomNav.tsx
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/pages/book/detail/index.tsx
  src/pages/index.tsx
  src/pages/recruit/index.tsx
Labels: ✨ Feature

#178 refactor: 유저 전용페이지에 url을 통해 비 로그인 유저가 페이지 접근시 막기
  src/pages/book/feed/index.tsx
  src/pages/book/record/index.tsx
  src/pages/book/record/select.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/recommend/game.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
  src/pages/recruit/write.tsx
Labels: 🔨 Refactor

#179 refactor: bottom nav bar
  src/components/common/BottomNav.tsx
Labels: 🔨 Refactor

#183 feat: 그룹 가입/탈퇴 api 연결
  src/api/main.ts
  src/api/recruit.ts
  src/components/common/Avartar.tsx
  src/components/common/ImageComponent.tsx
  src/components/common/Modal.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/pages/recruit/detail/index.tsx
  src/recoil/modal.ts
  src/types/recruit.d.ts
  tailwind.config.js
Labels: 🔑 API, ✨ Feature

#186 fix: 메인 페이지 hydration error 해결
  src/pages/index.tsx
Labels: 🐞 BugFix

#188 Api/#184 myprofile
  src/api/record.ts
  src/api/recruit.ts
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: 🔑 API, ✨ Feature

#187 feat: 독서 모임 상세페이지 모임장 권한 구현
  src/api/main.ts
  src/api/recruit.ts
  src/components/common/Header.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/RecruitStatusSelectModal.tsx
  src/pages/recruit/detail/index.tsx
  src/recoil/modal.ts
Labels: 🔑 API, ✨ Feature

#191 Feat/#189 main to feed
  src/api/main.ts
  src/api/record.ts
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
  src/types/record.d.ts
Labels: 🔨 Refactor, 🔑 API, ✨ Feature

#196 feat: 도서 선택 페이지 구현
  src/components/book/record/SelectModal.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/pages/book/record/search.tsx
  src/pages/book/record/select.tsx
  src/recoil/modal.ts
  src/types/modal.d.ts
Labels: ✨ Feature

#201 design: 메인 컬러 변수 설정 및 일괄 변경
  src/components/book/record/SelectModal.tsx
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/recruit/RecruitOpenForm.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/RecruitStatusSelectModal.tsx
  src/layout/BookSelectLayout.tsx
  src/layout/ProfileLayout.tsx
  src/pages/book/detail/index.tsx
  src/pages/book/record/index.tsx
  src/pages/book/record/select.tsx
  src/pages/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myrecruit.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
  src/pages/recruit/write.tsx
  tailwind.config.js
Labels: 💄Design

#199 Feat/#197 userpage
  src/api/bookshelf.ts
  src/api/profile.ts
  src/api/record.ts
  src/components/common/BookShelfPreview.tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/layout/ProfileLayout.tsx
  src/pages/book/record/select.tsx
  src/pages/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/types/modal.ts
Labels: ✨ Feature

#207 fix: 라우트 경로 수정
  src/components/common/ListItem/SearchResultListItem.tsx
Labels: 🐞 BugFix

#203 refactor: 도서 검색 시 작가 데이터가 없는 경우
  src/components/common/ListItem/SearchResultListItem.tsx
Labels: 🔨 Refactor

#204 fix: 로그인 성공 시 로그인 실패했습니다 render 되는 문제
  src/pages/oauth/callback/kakao.tsx
Labels: 🐞 BugFix

#202 feat: 독서 모임 수정 페이지
  src/api/recruit.ts
  src/components/recruit/RecruitForm.tsx
  src/components/recruit/RecruitFormUserInput.tsx
  src/hooks/useGroupForm.ts
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/update.tsx
  src/pages/recruit/write.tsx
  src/types/recruit.d.ts
Labels: ✨ Feature

#209 Feat/#208 mypage
  src/api/bookshelf.ts
  src/api/record.ts
  src/components/common/Modal.tsx
  src/layout/ProfileLayout.tsx
  src/pages/book/detail/index.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/recoil/modal.ts
  src/types/modal.ts
Labels: ✨ Feature

#217 refactor: isAuthorized 체크 Link -> useRouter로 변경
  src/components/common/BookShelfPreview.tsx
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/pages/book/detail/index.tsx
Labels: 🐞 BugFix

#211 feat: onboarding 페이지 구현
  src/layout/Layout.tsx
  src/pages/index.tsx
  src/pages/onboarding/index.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: ✨ Feature, 💄Design

#215 design: bottom nav bar
  public/images/bottomNavBar/group-off.svg
  public/images/bottomNavBar/group-on.svg
  public/images/bottomNavBar/home-off.svg
  public/images/bottomNavBar/home-on.svg
  public/images/bottomNavBar/profile-off.svg
  public/images/bottomNavBar/profile-on.svg
  public/images/bottomNavBar/record-off.svg
  public/images/bottomNavBar/record-on.svg
  public/images/bottomNavBar/search-off.svg
  public/images/bottomNavBar/search-on.svg
  src/components/common/BottomNav.tsx
Labels: 💄Design

#223 Design/#220 private
  src/api/recruit.ts
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
Labels: 💄Design

#225 feat: 네비게이션 적용, 조건식 수정
  src/pages/book/record/index.tsx
Labels: ✨ Feature

#228 feat: feed 구현
  src/api/main.ts
  src/api/record.ts
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/main/mainRecordFeed/FeedItem.tsx
  src/components/main/mainRecordFeed/RecordFeedList.tsx
  src/hooks/useInput.ts
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
  src/pages/book/record/index.tsx
  src/types/record.d.ts
Labels: ✨ Feature

#229 feat: 나의 모임 구현
  src/api/recruit.ts
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
  src/pages/profile/myrecruit.tsx
Labels: ✨ Feature

#231 feat: gpt 추천 페이지 구현
  next.config.js
  public/images/bookRecommend/bookshelfIcon.svg
  public/images/bookRecommend/recommendCharacter.png
  src/api/recommend.ts
  src/components/recommend/BookRecommendGuide.tsx
  src/components/recommend/RecommendComplete.tsx
  src/components/recommend/RecommendLoading.tsx
  src/layout/RecommendLayout.tsx
  src/pages/index.tsx
  src/pages/onboarding/index.tsx
  src/pages/recommend/game.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/intro.tsx
  src/pages/recommend/random.tsx
  src/pages/recommend/result.tsx
  src/pages/recommend/userinput.tsx
  src/recoil/recommend.ts
  src/types/recommend.d.ts
  tailwind.config.js
Labels: 🔑 API, ✨ Feature, 💄Design

#236 fix: 추천 페이지 이미 담은 책일 때 에러 처리
  src/pages/recommend/result.tsx
Labels: 🐞 BugFix

#237 feat: 그룹 멤버 관련 기능 구현
  src/api/main.ts
  src/api/recruit.ts
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/pages/recruit/detail/index.tsx
  src/pages/recruit/detail/member.tsx
  src/recoil/modal.ts
  src/types/recruit.d.ts
Labels: 🔑 API, ✨ Feature

#239 fix: 모임 참여/탈퇴 로딩 중일 때 disabled 처리
  src/components/recruit/detail/RecruitParticipationControl.tsx
Labels: 🐞 BugFix

#238 Feat/#230 profile to feed
  src/api/record.ts
  src/pages/book/feed/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
Labels: ✨ Feature

#242 Design/#241 record
  public/images/record/camera.svg
  public/images/record/delete.svg
  public/images/record/plus.svg
  src/components/book/record/Calendar.module.css
  src/pages/book/record/index.tsx
Labels: 💄Design

#244 design: 로그인 페이지
  public/images/kakao-logo.svg
  src/components/auth/LoginButton.tsx
  src/pages/login/index.tsx
  src/styles/globals.css
Labels: 💄Design

#248 design: 독서 모임 조회 페이지
  public/images/reading-group-illustration.svg
  src/pages/recruit/index.tsx
Labels: 💄Design

#258 design: 아이콘 추가, 글자색 변경
  public/images/feed/feed-left.svg
  public/images/feed/feed-right.svg
  src/pages/book/feed/index.tsx
Labels: 💄Design

#259 design/#243-profile
  public/images/profile/back-arrow.svg
  public/images/profile/logout.svg
  public/images/profile/pencil.svg
  src/layout/ProfileLayout.tsx
  src/pages/profile/edit.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
Labels: 💄Design

#257 fix: 메인 인기 모임 쿼리 키에 group Id 추가
  src/components/main/bestRecruit/BestRecruitListItem.tsx
Labels: 🐞 BugFix

#254 design: 메인 추천 책장 책 사이즈 통일
  src/components/common/BookShelfPreview.tsx
  tailwind.config.js
Labels: 💄Design

#253 design: gpt 책 추천 페이지 디자인 변경 사항 적용
  public/images/back-button.svg
  public/images/header/back-button-white.svg
  public/images/header/back-button.svg
  src/api/recommend.ts
  src/components/common/Header.tsx
  src/components/recommend/RecommendComplete.tsx
  src/components/recommend/RecommendLoading.tsx
  src/components/recommend/RecommendResultModal.tsx
  src/pages/recommend/result.tsx
  src/pages/recommend/userinput.tsx
  src/recoil/modal.ts
  tailwind.config.js
Labels: 💄Design

#250 fix: 로그인한 유저는 로그인 페이지 접근 금지
  src/pages/login/index.tsx
Labels: 🐞 BugFix

#252 design: Bottom Nav Bar 수정
  src/components/common/BottomNav.tsx
Labels: 💄Design

#261 design & fix : 아이콘 삽입, 피드 -> 도서 상세 넘어가지 않는 오류 해결
  public/images/detail/down-arrow.svg
  public/images/detail/left-arrow.svg
  public/images/detail/upper-arrow.svg
  src/pages/book/detail/index.tsx
  src/pages/book/feed/index.tsx
Labels: 🐞 BugFix, 💄Design

#265 Fix/#263 profile
  src/layout/ProfileLayout.tsx
  src/pages/profile/index.tsx
Labels: 🐞 BugFix, 💄Design

#269 design: 모달 아이콘 추가
  public/images/exit.svg
  public/images/info.svg
  src/components/book/record/SelectModal.tsx
Labels: 💄Design

#267 design: 로그인 페이지 로고 설정
  public/images/login-logo.svg
  src/pages/login/index.tsx
Labels: 💄Design

#272 design: 독서 모임 페이지 아이콘 적용
  public/images/group/edit-pencil.svg
  public/images/group/spread.svg
  src/pages/recruit/detail/index.tsx
Labels: 💄Design

#271 design: 페이지 max-width 설정
  src/pages/book/search/index.tsx
  src/pages/recruit/index.tsx
Labels: 💄Design

#277 design: 반응형적용
  src/pages/book/record/select.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
Labels: 💄Design

#276 design: 독서 모임 상세 페이지 디자인 세부 사항 적용
  src/pages/recruit/detail/index.tsx
Labels: 💄Design

#279 fix: 이미지 경로 수정
  src/components/common/SearchInput.tsx
Labels: 🐞 BugFix

#282 Fix/#280 myrecruit
  src/api/recruit.ts
  src/pages/profile/myrecruit.tsx
Labels: 🐞 BugFix

#284 feat: 독서 모임 개설, 수정 페이지
  src/api/recruit.ts
  src/components/recruit/RecruitForm.tsx
  src/pages/recruit/write.tsx
Labels: ✨ Feature

#285 design: 독서 모임 개설, 수정 페이지
  public/images/not-select-arrow.svg
  public/images/select-arrow.svg
  src/components/recruit/RecruitFormUserInput.tsx
Labels: 💄Design

#290 fix: 스크롤이 최 하단 상태일 때 보이는 리스트 아이템 수정 시 반영 안됨
  src/components/recruit/RecruitInfinityScrollLists.tsx
Labels: 🐞 BugFix

#294 refactor: 독서 모임 조회페이지 currentPage data type 수정
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/types/recruit.d.ts
Labels: 🔨 Refactor

#292 fix: 독서 모임 개설, 수정 후 refetch 하는 동안 comment render
  src/components/common/Header.tsx
  src/components/recruit/RecruitInfinityScrollLists.tsx
  src/pages/recruit/index.tsx
  src/pages/recruit/update.tsx
  src/pages/recruit/write.tsx
Labels: 🐞 BugFix

#299 design: 도서 상세 페이지 아이콘 변경
  public/images/detail/back.svg
  public/images/detail/bookshelf.svg
  public/images/detail/down-arrow.svg
  public/images/detail/left-arrow.svg
  public/images/detail/upper-arrow.svg
  src/pages/book/detail/index.tsx
Labels: 💄Design

#301 design: 독서 기록 페이지 아이콘 수정
  public/images/record/delete.svg
  public/images/record/hashtag-delete.svg
  src/pages/book/record/index.tsx
Labels: 💄Design

#296 design: 로그인 유저 추천 페이지 bottom nav bar 제거
  src/layout/RecommendLayout.tsx
  src/pages/recommend/index.tsx
  src/pages/recommend/userinput.tsx
Labels: 💄Design

#311 design: 프로필 수정 페이지 디자인 적용
  public/images/profile/edit/back.svg
  public/images/profile/edit/delete.svg
  public/images/profile/edit/image.svg
  src/pages/profile/edit.tsx
Labels: 💄Design

#314 design: 변경된 디자인 적용, 아이콘 적용
  public/images/profile/layout/edit.svg
  public/images/profile/layout/logout.svg
  src/layout/ProfileLayout.tsx
Labels: 💄Design

#316 design: 관련 기록 없을 때 컴포넌트
  src/pages/book/detail/index.tsx
Labels: 💄Design

#318 design: 수정된 디자인 적용
  public/images/record/select/exit.svg
  public/images/record/select/info.svg
  src/components/book/record/SelectModal.tsx
  src/components/common/Header.tsx
  src/layout/BookSelectLayout.tsx
  src/pages/book/record/select.tsx
Labels: 💄Design

#309 feat: 변경된 추천 api 적용
  src/api/book.ts
  src/api/recommend.ts
  src/components/recommend/RecommendComplete.tsx
  src/components/recommend/RecommendResultModal.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
  src/recoil/recommend.ts
  src/types/book.d.ts
  src/types/recommend.d.ts
Labels: 🔑 API, ✨ Feature

#304 fix: 도서 검색 페이지
  src/components/book/search/InfinityScrollLists.tsx
  src/components/common/SearchInput.tsx
  src/pages/book/search/index.tsx
Labels: 🐞 BugFix

#306 design: 독서 모임 조회 페이지 상단 일러스트 not fixed
  src/pages/recruit/index.tsx
Labels: 💄Design

#330 fix: bottom nav 기록 as 제거 및 경고 제거
  src/components/common/BottomNav.tsx
Labels: 🐞 BugFix

#328 design: 모달 반응형으로 변경
  src/components/common/Modal.tsx
  src/components/recruit/detail/RecruitParticipationControl.tsx
  src/components/recruit/detail/member/MemberListItem.tsx
  src/pages/recruit/detail/index.tsx
Labels: 💄Design

#327 design: 추천 페이지 일러스트 적용
  public/images/bookRecommend/background1.svg
  public/images/bookRecommend/background2.svg
  public/images/bookRecommend/background3.svg
  public/images/bookRecommend/recommendCharacter.png
  public/images/bookRecommend/recommendCharacter.svg
  public/images/bookRecommend/recommendGuideCharacter.svg
  public/images/bookRecommend/recommendResultCharacter.svg
  src/components/main/bestRecruit/BestRecruitListItem.tsx
  src/components/recommend/BookRecommendGuide.tsx
  src/components/recommend/RecommendResultModal.tsx
  src/pages/recommend/complete.tsx
  src/pages/recommend/userinput.tsx
Labels: 💄Design

#308 refactor: 스타일 단위를 px에서 rem으로 수정
  src/components/common/BookShelfPreview.tsx
  src/components/common/ListItem/ReadingGroupRecruitment .tsx
  src/components/common/ListItem/SearchResultListItem.tsx
  src/components/common/Modal.tsx
  src/components/common/SearchInput.tsx
  src/components/common/Tab/TabItem.tsx
  src/components/recruit/RecruitForm.tsx
  src/pages/book/search/index.tsx
  src/pages/recruit/index.tsx
Labels: 🔨 Refactor

#333 design: 온보딩 페이지 디자인 변경사항 적용
  public/images/onboarding/onboarding2.svg
  public/images/onboarding/onboarding3.svg
  src/pages/onboarding/index.tsx
  src/styles/globals.css
Labels: 💄Design

#337 design: 도서 검색 페이지 아이콘 설정 및 디자인 수정
  public/images/bookSearch/clear.svg
  public/images/bookSearch/search.svg
  public/images/close.svg
  public/images/search.svg
  src/components/common/SearchInput.tsx
  src/pages/book/search/index.tsx
Labels: 💄Design

#338 design: 독서 모임 조회 페이지 아이콘 설정
  public/images/group/people-white.svg
  src/pages/recruit/index.tsx
Labels: 💄Design

#340 refacotr: main color 반영
  src/components/book/record/Calendar.module.css
  src/components/common/BottomNav.tsx
  src/components/recruit/RecruitForm.tsx
  src/pages/profile/index.tsx
  src/pages/profile/myfeed.tsx
Labels: 🔨 Refactor
