Repository darakbooks-project/darakbooks-FE, pull requests merged in 2023-08, with the labels that each got.

#519 feat: 독서기록 시 이미지 지정 안할 시 책 표지 자동지정
  src/pages/book/record/index.tsx
Labels: ✨ Feature

#521 fix: 추천 책장 오류 멘트 조건 수정
  src/components/main/recommendBookShelf/BookShelfPreview.tsx
Labels: 🐞 BugFix

#523 feat: og:image content 추가
  public/images/seo/og-image.png
  src/components/common/Seo.tsx
Labels: ✨ Feature

#525 design: og:image 이미지 변경
  public/images/seo/og-image.png
Labels: 💄Design
